export enum movementReport {
    REPORT_CREATION = 'REPORTADO',
    VALIDATION = 'VALIDADO',
    REACTIVATION = 'REACTIVADO',
    ANULATION = 'ANULADO',
    ASSIGNMENT_ANALYST = 'ASIGNADO A ANALISTA',
    REASSIGNMENT_ANALYST = 'REASIGNADO A ANALISTA',
    RETURN_CASE_ANALYST = 'RETORNADO A ANALISTA',
    ASSIGNMENT_INVESTIGATOR = 'ASIGNADO A INVESTIGADOR',
    CASE_RAISED_SYNERGY_COMMITTEE = 'CASO ELEVADO A COMITÉ DE SINERGIA',
    CASE_RESCHEDULED_SYNERGY = 'CASO REPROGRAMADO EN SINERGIA',
    SOLUTION_CASE_SYNERGY = 'CASO SOLUCIONADO EN SINERGIA'
};